$skills = [
  {
    "action_name": "Malefic",
    "level_acquired": "Lv. 1",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage with a potency of 150.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/183ab49e5ed43f37889be8427bf9a4c308cfa748.png"
  },
  {
    "action_name": "Benefic",
    "level_acquired": "Lv. 2",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "30y 0y",
    "effect": "Restores target's HP. Cure Potency: 500 Additional Effect: 15% chance next Benefic II will restore critical HP Duration: 15s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/23d16903c44b621e2e0d68f608a813fc2a5b1055.png"
  },
  {
    "action_name": "Combust",
    "level_acquired": "Lv. 4",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage over time. Potency: 50Duration: 30s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b5a34001aef4b3dad1eaf5864146d890464e3163.png"
  },
  {
    "action_name": "Lightspeed",
    "level_acquired": "Lv. 6",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Reduces cast times for spells by 2.5 seconds. Duration: 15s Maximum Charges: 2",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8a41b60865844ff8a5eeb76aaf885b8e8b0ad5b6.png"
  },
  {
    "action_name": "Helios",
    "level_acquired": "Lv. 10",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "700 MP",
    "radius": "0y 20y",
    "effect": "Restores own HP and the HP of all nearby party members. Cure Potency: 400",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4de44df1a7ba71fdd94b5e4d26b378c8895c594a.png"
  },
  {
    "action_name": "Ascend",
    "level_acquired": "Lv. 12",
    "type_of_action": "Spell",
    "cast": "8s",
    "recast": "2.5s",
    "mp_cost": "2400 MP",
    "radius": "30y 0y",
    "effect": "Resurrects target to a weakened state.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/d7284036ab2b7f0eb020ef471eb9b1de1ccbb02d.png"
  },
  {
    "action_name": "Essential Dignity",
    "level_acquired": "Lv. 15",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "40s",
    "mp_cost": "0",
    "radius": "30y 0y",
    "effect": "Restores target's HP. Cure Potency: 400 Potency increases up to 900 as the target's HP decreases, reaching its maximum value when the target has 30% HP or less. Maximum Charges: 3",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/6900c041afabd698273f5ca3c99d64574bdfacf6.png"
  },
  {
    "action_name": "Benefic II",
    "level_acquired": "Lv. 26",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "700 MP",
    "radius": "30y 0y",
    "effect": "Restores target's HP. Cure Potency: 800",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/f77f8fb51548637c94db4f1b8e90fc7b1a4ee55f.png"
  },
  {
    "action_name": "Astral Draw",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "55s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Draws the Balance, the Arrow, the Spire, and the Lord of Crowns from your divining deck. Additional Effect: Restores 20% of maximum MPUpon execution, Play I changes to The Balance, Play II changes to The Arrow, Play III changes to The Spire, Minor Arcana changes to Lord of Crowns, and Astral Draw changes to Umbral Draw.Shares a recast timer with Umbral Draw.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/ca9495b5dd2708d088f8180b433b812580622dcb.png"
  },
  {
    "action_name": "Umbral Draw",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "55s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Draws the Spear, the Bole, the Ewer, and the Lady of Crowns from your divining deck. Additional Effect: Restores 20% of maximum MPUpon execution, Play I changes to The Spear, Play II changes to The Bole, Play III changes to The Ewer, Minor Arcana changes to Lady of Crowns, and Umbral Draw changes to Astral Draw.Shares a recast timer with Astral Draw.※This action cannot be assigned to a hotbar.※Astral Draw changes to Umbral Draw when requirements for execution are met.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/3a5badd54650309c03a120ea6906ad51276e8c6e.png"
  },
  {
    "action_name": "Play I",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Plays the drawn arcanum after executing Astral Draw or Umbral Draw. Astral Draw Effect: Action changes to The Balance. Umbral Draw Effect: Action changes to The Spear.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/aa32f90984104b56be403963081f119244df50a8.png"
  },
  {
    "action_name": "Play II",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Plays the drawn arcanum after executing Astral Draw or Umbral Draw. Astral Draw Effect: Action changes to The ArrowUmbral Draw Effect: Action changes to The Bole",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1d7b124a1b665b5be6db3759a2f5060eef40b89d.png"
  },
  {
    "action_name": "Play III",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Plays the drawn arcanum after executing Astral Draw or Umbral Draw. Astral Draw Effect: Action changes to The SpireUmbral Draw Effect: Action changes to The Ewer",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/59c09c6f090fb75d16bb4f906793b951fd58b4cf.png"
  },
  {
    "action_name": "Aspected Benefic",
    "level_acquired": "Lv. 34",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "30y 0y",
    "effect": "Restores target's HP. Cure Potency: 250 Additional Effect: Regen Cure Potency: 250 Duration: 15s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/9bef02f2854edbe020ce99626c711e66d18e5f85.png"
  },
  {
    "action_name": "Aspected Helios",
    "level_acquired": "Lv. 40",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "800 MP",
    "radius": "0y 20y",
    "effect": "Restores own HP and the HP of all nearby party members. Cure Potency: 250Additional Effect: RegenCure Potency: 150Duration: 15s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c4b31e905fbbbd9b79d5afc5c5aed9a89d46f788.png"
  },
  {
    "action_name": "Gravity",
    "level_acquired": "Lv. 45",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 8y",
    "effect": "Deals unaspected damage with a potency of 120 to target and all enemies nearby it.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c5048acc0cf1b937307241ff27f77ad032505872.png"
  },
  {
    "action_name": "Combust II",
    "level_acquired": "Lv. 46",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage over time. Potency: 60 Duration: 30s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/3f1ca32d6772490ce1a8cbf36fc80c4596dec7ee.png"
  },
  {
    "action_name": "Synastry",
    "level_acquired": "Lv. 50",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "30y 0y",
    "effect": "Generate an aetheric bond with target party member. Each time you cast a single-target healing spell on yourself or a party member, the party member with whom you have the bond will also recover HP equaling 40% of the original spell. Duration: 20s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/556bdf27e11b05ed3d2c48c9ab895af933d07ab9.png"
  },
  {
    "action_name": "Divination",
    "level_acquired": "Lv. 50",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Increases damage dealt by self and nearby party members by 6%. Duration: 20sAdditional Effect: Grants DiviningDuration: 30s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4df3bcac0369619901583d1b18c13e1cf160e8b5.png"
  },
  {
    "action_name": "Malefic II",
    "level_acquired": "Lv. 54",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage with a potency of 160.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b3b405ffabff79b88db294cae3aff6296d9f743a.png"
  },
  {
    "action_name": "Collective Unconscious",
    "level_acquired": "Lv. 58",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Creates a celestial ring 8 yalms around the caster. Duration: 18s Additional Effect: Reduces damage taken by 10% for self and any party members within 30 yalms and applies Wheel of Fortune to self and any party members within 8 yalms Duration: 5s Wheel of Fortune Effect: Regen Cure Potency: 100 Duration: 15s Effects will be applied continuously to self and all party members standing within the celestial ring. Collective Unconscious effect ends upon using another action or moving (including facing a different direction). Cancels auto-attack upon execution.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8c6c1d8dd2025d1019e16133be9b5c8bc9871201.png"
  },
  {
    "action_name": "Celestial Opposition",
    "level_acquired": "Lv. 60",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 20y",
    "effect": "Restores own HP and the HP of all nearby party members. Cure Potency: 200 Additional Effect: Regen Cure Potency: 100 Duration: 15s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b0fa77347891a32179c547797e6deed79e9ef47a.png"
  },
  {
    "action_name": "Earthly Star",
    "level_acquired": "Lv. 62",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "30y 20y",
    "effect": "Deploys an Earthly Star in the designated area and grants the effect of Earthly Dominance. Duration: 10sExecuting Stellar Detonation while under the effect of Earthly Dominance creates a Stellar Burst dealing unaspected damage with a potency of 205 to all nearby enemies. Also restores own HP and the HP of all nearby party members.Cure Potency: 540After 10s, Earthly Dominance effect is changed to Giant Dominance.Duration: 10sWaiting 10s or executing Stellar Detonation while under the effect of Giant Dominance creates a Stellar Explosion dealing unaspected damage with a potency of 310 to all nearby enemies. Also restores own HP and the HP of all nearby party members.Cure Potency: 720",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7012ee74c18fa7f0e6a087d778701560a5553322.png"
  },
  {
    "action_name": "Stellar Detonation",
    "level_acquired": "Lv. 62",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "3s",
    "mp_cost": "0",
    "radius": "0y 20y",
    "effect": "While under the effect of Earthly Dominance, detonates the currently deployed Earthly Star, creating a Stellar Burst that deals unaspected damage with a potency of 205 to all nearby enemies.Additional Effect: Restores own HP and the HP of all nearby party membersCure Potency: 540While under the effect of Giant Dominance, detonates the currently deployed Earthly Star, creating a Stellar Explosion that deals unaspected damage with a potency of 310 to all nearby enemies.Additional Effect: Restores own HP and the HP of all nearby party membersCure Potency: 720",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5d3bd4b689787c566897a86b425e9e5149123df2.png"
  },
  {
    "action_name": "Malefic III",
    "level_acquired": "Lv. 64",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage with a potency of 190.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b1a9eac4e36df41bc621c096cfb001e32a970fd7.png"
  },
  {
    "action_name": "Minor Arcana",
    "level_acquired": "Lv. 70",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Plays the drawn arcanum after executing Astral Draw or Umbral Draw. Astral Draw Effect: Action changes to Lord of Crowns. Umbral Draw Effect: Action changes to Lady of Crowns.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c853db515158ad161d5ef8b9a84cdc5af02b6850.png"
  },
  {
    "action_name": "Combust III",
    "level_acquired": "Lv. 72",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage over time. Potency: 70 Duration: 30s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e349d6ef0e8f566a09bc7c1220876e25707ae721.png"
  },
  {
    "action_name": "Malefic IV",
    "level_acquired": "Lv. 72",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage with a potency of 230.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/ff7d87f8fcd5c702dc0723ba9fb286b2050e968c.png"
  },
  {
    "action_name": "Celestial Intersection",
    "level_acquired": "Lv. 74",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "30s",
    "mp_cost": "0",
    "radius": "30y 0y",
    "effect": "Restores own or target party member's HP. Cure Potency: 200 Additional Sect Effect: Erects a magicked barrier which nullifies damage equaling 200% of the amount of HP restored Duration: 30s Maximum Charges: 2",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5ee8bc24d9a8ee766b7dda50cbcb29be15727990.png"
  },
  {
    "action_name": "Horoscope",
    "level_acquired": "Lv. 76",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Reads your fortune and those of nearby party members, granting them Horoscope. Duration: 10s Effect upgraded to Horoscope Helios upon receiving the effects of Helios or Helios Conjunction. Duration: 30s Restores the HP of those under either effect when the cards are read a second time or the effect expires. Horoscope Cure Potency: 200 Horoscope Helios Cure Potency: 400",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4c87d9b89ed28f32863f8c094717d53ceeba741a.png"
  },
  {
    "action_name": "Horoscope",
    "level_acquired": "Lv. 76",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Restores own HP and the HP of all nearby party members. Potency is determined by the Horoscope effect of party members. Effect expires upon execution. Horoscope Potency: 200 Horoscope Helios Potency: 400",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/304809845293aaad1c232a7d143732b182e34197.png"
  },
  {
    "action_name": "Neutral Sect",
    "level_acquired": "Lv. 80",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Increases healing magic potency by 20%. Duration: 20s Additional Effect: When casting Aspected Benefic or Helios Conjunction, erects a magicked barrier which nullifies damage Aspected Benefic Effect: Nullifies damage equaling 250% of the amount of HP restored Helios Conjunction Effect: Nullifies damage equaling 125% of the amount of HP restored Duration: 30s Additional Effect: Grants Suntouched Duration: 30s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5a81be793ffaa939b52917ef026f6652a2227498.png"
  },
  {
    "action_name": "Fall Malefic",
    "level_acquired": "Lv. 82",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 0y",
    "effect": "Deals unaspected damage with a potency of 270.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/06b9d2b4c1b2e0aae4f345dfeeaefd76e86ec789.png"
  },
  {
    "action_name": "Gravity II",
    "level_acquired": "Lv. 82",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "400 MP",
    "radius": "25y 8y",
    "effect": "Deals unaspected damage with a potency of 140 to target and all enemies nearby it.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7a5cfc1f8baa06ffb818bee6f8cde7cd0db857fa.png"
  },
  {
    "action_name": "Exaltation",
    "level_acquired": "Lv. 86",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "30y 0y",
    "effect": "Reduces damage taken by self or target party member by 10%. Duration: 8s Additional Effect: Restores HP at the end of the effect's duration Cure Potency: 500",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/6b48700e107bcfe9620f773da5896b514e89f9a2.png"
  },
  {
    "action_name": "Macrocosmos",
    "level_acquired": "Lv. 90",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "180s",
    "mp_cost": "600 MP",
    "radius": "0y 20y",
    "effect": "Deals unaspected damage to all nearby enemies with a potency of 270 for the first enemy, and 40% less for all remaining enemies. Additional Effect: Grants Macrocosmos to self and all nearby party members Duration: 15s For the effect's duration, 50% of damage taken is compiled. Restores HP equal to a cure of 200 potency plus compiled damage when the effect expires or upon execution of Microcosmos. Amount restored cannot exceed the target's maximum HP. Recast timer cannot be affected by status effects or gear attributes.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/69474c8e5dfbf0236360e4982bed44a0ea9b523f.png"
  },
  {
    "action_name": "Microcosmos",
    "level_acquired": "Lv. 90",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 20y",
    "effect": "Triggers the healing effect of Macrocosmos, restoring HP equal to a cure of 200 potency plus 50% of compiled damage. Amount restored cannot exceed the target's maximum HP.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/96ad13792128386a54c9a3d5215b0f6bbb0af2aa.png"
  },
  {
    "action_name": "Oracle",
    "level_acquired": "Lv. 92",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "25y 5y",
    "effect": "Deals unaspected damage to target and all enemies nearby it with a potency of 860 for the first enemy and 50% less for all remaining enemies. Can only be executed while Divining.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7c826ef697cd5d5934661e9238dd5ba0ad607e9d.png"
  },
  {
    "action_name": "Helios Conjunction",
    "level_acquired": "Lv. 96",
    "type_of_action": "Spell",
    "cast": "1.5s",
    "recast": "2.5s",
    "mp_cost": "800 MP",
    "radius": "0y 20y",
    "effect": "Restores own HP and the HP of all nearby party members. Cure Potency: 250 Additional Effect: Regen Cure Potency: 175 Duration: 15s",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/20768aed61f83aeae04632231cba41ae889e187f.png"
  },
  {
    "action_name": "Sun Sign",
    "level_acquired": "Lv. 100",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Reduces damage taken by self and nearby party members by 10%. Duration: 15s Can only be executed while Suntouched.",
    "class_name": "astrologian",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/9b0527d5ad6cdb263a912b463d4ff12bd13e9fea.png"
  }
]
