$skills = [
  {
    "action_name": "Hard Slash",
    "level_acquired": "Lv. 1",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 300.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5c0fef99ef9100285ede6dbc62a5c35cea188d7c.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Syphon Strike",
    "level_acquired": "Lv. 2",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 240.Combo Action: Hard SlashCombo Potency: 380Combo Bonus: Restores MP",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e2a305d72e05ef339e0692bd5f7ed9626b6eb9ea.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Unleash",
    "level_acquired": "Lv. 6",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Deals unaspected damage with a potency of 120 to all nearby enemies.Additional Effect: Increased enmity",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/600c6a17bd8c4e08c783d1fb8891f12eea132a9a.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Grit",
    "level_acquired": "Lv. 10",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "2s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Significantly increases enmity generation.Effect ends upon reuse.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b6d1592d4fcbcafe1e3b0958d688c50346fe2bd4.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Release Grit",
    "level_acquired": "Lv. 10",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Cancels the effect of Grit.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/13a97691011df3c616e3181fd21b5f6805ce5799.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Unmend",
    "level_acquired": "Lv. 15",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Deals unaspected damage with a potency of 150.Additional Effect: Increased enmityAdditional Effect: Reduces the recast time of Shadowstride by 5 seconds",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/6203d55695d1cdde37d875f7b4b4253606266ad0.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Souleater",
    "level_acquired": "Lv. 26",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 260.Combo Action: Syphon StrikeCombo Potency: 480Combo Bonus: Restores own HPCure Potency: 300Combo Bonus: Increases Blood Gauge by 20",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8c6a197869a69116f52b41b3fef2ce03c29b5212.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Flood of Darkness",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "3000 MP",
    "radius": "10y 10y",
    "effect": "Deals unaspected damage with a potency of 100 to all enemies in a straight line before you.Additional Effect: Grants Darkside, increasing damage dealt by 10%Duration: 30sExtends Darkside duration by 30s to a maximum of 60s.Shares a recast timer with Edge of Darkness.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/438927fdaa593ec9d1bd020e1c60fad9ca495f3f.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Blood Weapon",
    "level_acquired": "Lv. 35",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Grants 3 stacks of Blood Weapon, each stack increasing Blood Gauge by 10 and restoring MP upon landing weaponskills or spells.Duration: 15sEffect does not stack when hitting multiple targets with a single attack.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c0c4dd65cec09b11aa7ecfecf6526aff4c59b83f.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Shadow Wall",
    "level_acquired": "Lv. 38",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Reduces damage taken by 30%.Duration: 15s",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7ea7904a9e066bb33d542755b5984ad78c711a45.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Stalwart Soul",
    "level_acquired": "Lv. 40",
    "type_of_action": "Spell",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Deals unaspected damage with a potency of 120 to all nearby enemies.Additional Effect: Increased enmityCombo Action: UnleashCombo Potency: 160Combo Bonus: Restores MPCombo Bonus: Increases Blood Gauge by 20",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/cc2fff4dcbf82d405c36a0d153fb28af5fcb9068.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Edge of Darkness",
    "level_acquired": "Lv. 40",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "3000 MP",
    "radius": "3y 0y",
    "effect": "Deals unaspected damage with a potency of 300.Additional Effect: Grants Darkside, increasing damage dealt by 10%Duration: 30sExtends Darkside duration by 30s to a maximum of 60s.Shares a recast timer with Flood of Darkness.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e62374eb5036fcaa1201fec390bc266620501abe.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Dark Mind",
    "level_acquired": "Lv. 45",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Reduces physical damage taken by 10% and magic damage taken by 20%.Duration: 10s",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/adb1f756a8cfa746f5ec2f97e487e41c06026a61.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Living Dead",
    "level_acquired": "Lv. 50",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "300s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Grants the effect of Living Dead.When HP is reduced to 0 while under the effect of Living Dead, instead of becoming KO'd, your status will change to Walking Dead.Living Dead Duration: 10sAdditional Effect: Restores HP with each weaponskill successfully delivered or spell castCure Potency: 1500While under the effect of Walking Dead, most attacks will not lower your HP below 1. If, before the Walking Dead timer runs out, an amount of HP totaling your maximum HP is restored, the effect will change to Undead Rebirth. If this amount is not restored, you will be KO'd.Walking Dead Duration: 10sWhile under the effect of Undead Rebirth, most attacks will not lower your HP below 1.Undead Rebirth Duration: Time remaining on Walking Dead",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/968fc4ccd880ca468fff7b34680e793a80ffdab1.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Salted Earth",
    "level_acquired": "Lv. 52",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "90s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Creates a patch of salted earth at your feet, dealing unaspected damage with a potency of 50 to any enemies who enter.Duration: 15s",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8c3e2f641cea5b3c0693034e6feafeff359341c5.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Shadowstride",
    "level_acquired": "Lv. 54",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "30s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Rush to a targeted enemy's location.Additional Effect: Increased enmityMaximum Charges: 2Cannot be executed while bound.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/52870f24b14efd37172003e974b8c45ca3d38010.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Abyssal Drain",
    "level_acquired": "Lv. 56",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "20y 5y",
    "effect": "Deals unaspected damage with a potency of 240 to target and all enemies nearby it.Additional Effect: Restores own HPCure Potency: 500Additional Effect: Restores MPShares a recast timer with Carve and Spit.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/17543c65847814b073fe6481402a347c7efc9225.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Carve and Spit",
    "level_acquired": "Lv. 60",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers a threefold attack with a potency of 540.Additional Effect: Restores own HPCure Potency: 500Additional Effect: Restores MPShares a recast timer with Abyssal Drain.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/6bbe53b6e1f87598b98967ae9d29e4337a7afadd.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Bloodspiller",
    "level_acquired": "Lv. 62",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 600.Blood Gauge Cost: 50",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4e5cbcae7dcf48cf8e3522d308f0c86df9114f0d.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Quietus",
    "level_acquired": "Lv. 64",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 240 to all nearby enemies.Blood Gauge Cost: 50",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/ea30bbaacc0da577820f8b027cec26738c1be840.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Dark Missionary",
    "level_acquired": "Lv. 66",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "90s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Reduces physical damage taken by 5% and magic damage taken by 10% for self and nearby party members.Duration: 15s",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1dc1a1d830e5355e2cd251531e85932c24ba1b8d.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Delirium",
    "level_acquired": "Lv. 68",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Grants 3 stacks of Delirium and Blood Weapon.Delirium Effect: Changes Bloodspiller to Scarlet Delirium and Quietus to ImpalementDuration: 15sBlood Weapon Effect: Each stack increases Blood Gauge by 10 and restores MP upon landing weaponskills or spellsDuration: 15sEffect does not stack when hitting multiple targets with a single attack.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/fbf4ae3878ecc04c6201114ce6b0aadf26bef857.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "The Blackest Night",
    "level_acquired": "Lv. 70",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "15s",
    "mp_cost": "3000 MP",
    "radius": "30y 0y",
    "effect": "Creates a barrier around self or target party member that absorbs damage totaling 25% of target's maximum HP.Duration: 7sGrants Dark Arts when barrier is completely absorbed.Dark Arts Effect: Consume Dark Arts instead of MP to execute Edge of Shadow or Flood of Shadow",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/f82c8fbcd6549c8cd72108a937aade172f8b98a8.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Flood of Shadow",
    "level_acquired": "Lv. 74",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "3000 MP",
    "radius": "10y 10y",
    "effect": "Deals unaspected damage with a potency of 160 to all enemies in a straight line before you.Additional Effect: Grants Darkside, increasing damage dealt by 10%Duration: 30sExtends Darkside duration by 30s to a maximum of 60s.Shares a recast timer with Edge of Shadow.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/de4960def285cc69e33455acae0f50808a6cd623.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Edge of Shadow",
    "level_acquired": "Lv. 74",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "3000 MP",
    "radius": "3y 0y",
    "effect": "Deals unaspected damage with a potency of 460.Additional Effect: Grants Darkside, increasing damage dealt by 10%Duration: 30sExtends Darkside duration by 30s to a maximum of 60s.Shares a recast timer with Flood of Shadow.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e4536e75673663bf1b91d1a78a565dabc2f041f6.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Living Shadow",
    "level_acquired": "Lv. 80",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Conjure a simulacrum of your darkside to fight alongside you.Duration: 20sAdditional Effect: Grants ScornDuration: 30sSimulacrum Attack Potency: 420Additional Effect: Simulacrum is able to execute Shadowbringer and DisesteemShadowbringer Potency: 570 for the first enemy, and 25% less for all remaining enemiesDisesteem Potency: 620 for the first enemy, and 25% less for all remaining enemies",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5150a7bff7be43d689f896e7be140f4720a23f6e.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Oblation",
    "level_acquired": "Lv. 82",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "30y 0y",
    "effect": "Reduces damage taken by target party member or self by 10%.Duration: 10sMaximum Charges: 2",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5a42ca000eb7ab0c80e3952539ed260af3d4c5e8.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Salt and Darkness",
    "level_acquired": "Lv. 86",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "20s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "All enemies standing in the corrupted patch of Salted Earth take additional unaspected damage with a potency of 500 for the first enemy, and 25% less for all remaining enemies.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/bb0216fb548f749ceb5bf25f071af462129be59b.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Shadowbringer",
    "level_acquired": "Lv. 90",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Deals unaspected damage to all enemies in a straight line before you with a potency of 600 for the first enemy, and 25% less for all remaining enemies.Maximum Charges: 2Can only be executed while under the effect of Darkside.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/bb5281f6fd7eb6900cbda1c39722b4d3c7e51b6e.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Shadowed Vigil",
    "level_acquired": "Lv. 92",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Reduces damage taken by 40%.Duration: 15sAdditional Effect: Grants VigilantDuration: 20sVigilant Effect: Restores HP when HP falls below 50% or upon effect duration expirationCure Potency: 1,200",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/093f2ddb0a06f04a76fe41fd5c31f7fceb46d2ea.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Scarlet Delirium",
    "level_acquired": "Lv. 96",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 620.Additional Effect: Restores MPCan only be executed while under the effect of Delirium.※This action cannot be assigned to a hotbar.※Bloodspiller changes to Scarlet Delirium while under the effect of Delirium.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/457d3fa4f25afb9c4494105c0afc15644bbaad7a.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Comeuppance",
    "level_acquired": "Lv. 96",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 720.Combo Action: Scarlet DeliriumAdditional Effect: Restores MPCan only be executed while under the effect of Delirium.※This action cannot be assigned to a hotbar.※Scarlet Delirium changes to Comeuppance when requirements for execution are met.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/cc157e7338d9b4c32f880aed1838519933bc6797.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Torcleaver",
    "level_acquired": "Lv. 96",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 820.Combo Action: ComeuppanceAdditional Effect: Restores MPCan only be executed while under the effect of Delirium.※This action cannot be assigned to a hotbar.※Comeuppance changes to Torcleaver when requirements for execution are met.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/2510476b643976c09c1b42f6eb9f011b7de6902c.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Impalement",
    "level_acquired": "Lv. 96",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 300 to all nearby enemies.Additional Effect: Restores MPCan only be executed while under the effect of Delirium.※This action cannot be assigned to a hotbar.※Quietus changes to Impalement when requirements for execution are met.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/77ef69ee0efdb439996373d7e47f2744a7604b10.png",
    "armor_type": "fending",
    "class_type": "melee"
  },
  {
    "action_name": "Disesteem",
    "level_acquired": "Lv. 100",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Deals physical damage to all enemies in a straight line before you with a potency of 1,000 for the first enemy, and 25% less for all remaining enemies.Can only be executed while Scorn is active.",
    "class_name": "darkknight",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/acf9474555312bfc65c8d4e8e93cf368f819f503.png",
    "armor_type": "fending",
    "class_type": "melee"
  }
]
