$skills = [
  {
    "action_name": "True Thrust",
    "level_acquired": "Lv. 1",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 230.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/a456526b20c613a31c9ff03a7cd8d69ab328a4c8.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Vorpal Thrust",
    "level_acquired": "Lv. 4",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 130.Combo Action: True Thrust or Raiden ThrustCombo Potency: 280",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/85a78cf7b49d80ab94aa206b385563ffa0222346.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Life Surge",
    "level_acquired": "Lv. 6",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "40s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Ensures critical damage for first weaponskill used while Life Surge is active.Duration: 5sIncreases damage dealt when under an effect that raises critical hit rate.Effect cannot be applied to damage over time.Additional Effect: Absorbs a portion of damage dealt as HPMaximum Charges: 2",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/eb7e59cbec93afbdf7a3cecd0e164c545ea8dec2.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Piercing Talon",
    "level_acquired": "Lv. 15",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Delivers a ranged attack with a potency of 200.Enhanced Piercing Talon Potency: 350",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b34933ec0ea122c75fd1deeb69f3b9df942dbdc1.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Disembowel",
    "level_acquired": "Lv. 18",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.Combo Action: True Thrust or Raiden ThrustCombo Potency: 250Combo Bonus: Grants Power SurgePower Surge Effect: Increases damage dealt by 10%Duration: 30s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/d5052c9c0d1bf846c9a4fb70497dd1cea97ceca6.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Full Thrust",
    "level_acquired": "Lv. 26",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 100.Combo Action: Vorpal ThrustCombo Potency: 380",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/34a78b866a4906267ee8f0e93457cb22b5550b9d.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Lance Charge",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Increases damage dealt by 10%.Duration: 20s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/cb90fa2f691cd58f5b068f6088550b3d56c2bd73.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Jump",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "30s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Delivers a jumping attack with a potency of 320. Returns you to your original position after the attack is made.Additional Effect: Grants Dive ReadyDuration: 15s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/15919e7dd2c5589a71f3c5115c3cb1e5b02f7572.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Elusive Jump",
    "level_acquired": "Lv. 35",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "30s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Executes a jump to a location 15 yalms behind you.Additional Effect: Grants Enhanced Piercing TalonDuration: 15sCannot be executed while bound.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/a13b9738eba1cfa6331a577992a05fbf8e29b12e.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Doom Spike",
    "level_acquired": "Lv. 40",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Delivers an attack with a potency of 110 to all enemies in a straight line before you.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1e6e09c76f8847d3caf2ee330400848219460dfa.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Winged Glide",
    "level_acquired": "Lv. 45",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Rush to a targeted enemy's location.Maximum Charges: 2Cannot be executed while bound.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/970713e35721fcecc8fce83a6064c984bdeb22c3.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Chaos Thrust",
    "level_acquired": "Lv. 50",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 100.140 when executed from a target's rear.Combo Action: DisembowelCombo Potency: 220Rear Combo Potency: 260Combo Bonus: Damage over timePotency: 40Duration: 24s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b77850f0a67953c4b4a13228788bdc1ec41c20fc.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Dragonfire Dive",
    "level_acquired": "Lv. 50",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "20y 5y",
    "effect": "Delivers a jumping fire-based attack to target and all enemies nearby it with a potency of 500 for the first enemy, and 50% less for all remaining enemies.Additional Effect: Grants Dragon's FlightDuration: 30sCannot be executed while bound.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b2d62c093eb2ccde88c41512eba79a759d3b1731.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Battle Litany",
    "level_acquired": "Lv. 52",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 30y",
    "effect": "Increases critical hit rate of self and nearby party members by 10%.Duration: 20s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/705282791cafca1896aafcb629217ccf272fa317.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Fang and Claw",
    "level_acquired": "Lv. 56",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.180 when executed from a target's flank.Combo Action: Heavens' ThrustCombo Potency: 300Flank Combo Potency: 340",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/bcf8b96ea7064ae0c532cb80fa44d59ec5fa9208.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Wheeling Thrust",
    "level_acquired": "Lv. 58",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.180 when executed from a target's rear.Combo Action: Chaotic SpringCombo Potency: 300Rear Combo Potency: 340",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/85d31ee98aca28156e6dbfcfc17473bb90d1c044.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Geirskogul",
    "level_acquired": "Lv. 60",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "15y 15y",
    "effect": "Delivers an attack to all enemies in a straight line before you with a potency of 280 for the first enemy, and 50% less for all remaining enemies.Additional Effect: Grants Life of the DragonLife of the Dragon Effect: Increases damage dealt by 15%Duration: 20sAdditional Effect: Grants Nastrond ReadyDuration: 20s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/9fd17ed870b46d4f1cb7dfbbfe36232a69ffab25.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Sonic Thrust",
    "level_acquired": "Lv. 62",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Delivers an attack with a potency of 100 to all enemies in a straight line before you.Combo Action: Doom Spike or Draconian FuryCombo Potency: 120Combo Bonus: Grants Power SurgePower Surge Effect: Increases damage dealt by 10%Duration: 30s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/86993377c3b82442fd98d9ccaf2c8e007b110d3e.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Drakesbane",
    "level_acquired": "Lv. 64",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 460.Combo Action: Wheeling Thrust or Fang and ClawCombo Bonus: Grants Draconian FireDuration: 30sCan only be executed after successfully landing Wheeling Thrust or Fang and Claw as a combo action.※This action cannot be assigned to a hotbar.※Wheeling Thrust and Fang and Claw change to Drakesbane when requirements for execution are met.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1bc31e46fb90bda5697cf272e0df8b9ac8086b13.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Mirage Dive",
    "level_acquired": "Lv. 68",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Delivers an attack with a potency of 380.Can only be executed when Dive Ready.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/838933d8bbe091490defd8b0c455c1b6cd553f21.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Nastrond",
    "level_acquired": "Lv. 70",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "2s",
    "mp_cost": "0",
    "radius": "15y 15y",
    "effect": "Delivers an attack to all enemies in a straight line before you with a potency of 720 for the first enemy, and 50% less for all remaining enemies.Can only be executed while Nastrond Ready.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8e8ee9ce030d0945ab1983fa282569bf9359e77b.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Coerthan Torment",
    "level_acquired": "Lv. 72",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Delivers an attack with a potency of 100 to all enemies in a straight line before you.Combo Action: Sonic ThrustCombo Potency: 150Combo Bonus: Grants Draconian FireDuration: 30s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/27c2b3ef23b6bbe6b322b8a0bade3e00e04727b1.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "High Jump",
    "level_acquired": "Lv. 74",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "30s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Delivers a jumping attack with a potency of 400. Returns you to your original position after the attack is made.Additional Effect: Grants Dive ReadyDuration: 15s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/43bde23e743d27c8dd8c0a29020671f33fbb1ac6.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Raiden Thrust",
    "level_acquired": "Lv. 76",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 320.Additional Effect: Sharpens the Firstminds' Focus by 1Can only be executed while under the effect of Draconian Fire.※This action cannot be assigned to a hotbar.※True Thrust changes to Raiden Thrust when requirements for execution are met.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e6c9b8537cca3034858fb078bb6100232c6e23c7.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Stardiver",
    "level_acquired": "Lv. 80",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "30s",
    "mp_cost": "0",
    "radius": "20y 5y",
    "effect": "Delivers a jumping fire-based attack to target and all enemies nearby it with a potency of 840 for the first enemy, and 40% less for all remaining enemies.Additional Effect: Grants Starcross ReadyDuration: 20sEffect ends when Life of the Dragon expires.Can only be executed while under the effect of Life of the Dragon.Cannot be executed while bound.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/65fe43d4e61e67defd885819e6f7d1c8fb1c9ea8.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Draconian Fury",
    "level_acquired": "Lv. 82",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Delivers an attack with a potency of 130 to all enemies in a straight line before you.Additional Effect: Sharpens the Firstminds' Focus by 1Can only be executed while under the effect of Draconian Fire.※This action cannot be assigned to a hotbar.※Doom Spike changes to Draconian Fury when requirements for execution are met.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8d26d75ca622ec9c3ebdb2c9810f3a8981f04710.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Heavens' Thrust",
    "level_acquired": "Lv. 86",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 160.Combo Action: Lance BarrageCombo Potency: 460",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/d710d7f61fe3638ab7d5bb12c6e58c2585c4faa7.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Chaotic Spring",
    "level_acquired": "Lv. 86",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.180 when executed from a target's rear.Combo Action: Spiral BlowCombo Potency: 300Rear Combo Potency: 340Combo Bonus: Damage over timePotency: 45Duration: 24s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/fa6d2bfbf0b127a283fa2ca3679b3dcb23515ee0.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Wyrmwind Thrust",
    "level_acquired": "Lv. 90",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "10s",
    "mp_cost": "0",
    "radius": "15y 15y",
    "effect": "Delivers an attack to all enemies in a straight line before you with a potency of 440 for the first enemy, and 50% less for all remaining enemies.Firstminds' Focus Cost: 2",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/40c1c2685a3b7778e1afe54476cfc68e6f2745fd.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Rise of the Dragon",
    "level_acquired": "Lv. 92",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "20y 5y",
    "effect": "Deals physical damage to target and all enemies nearby it with a potency of 550 for the first enemy, and 50% less for all remaining enemies.Can only be executed while under the effect of Dragon's Flight.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4d7cca717dd43f7598d848d99886ccaec3835bad.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Lance Barrage",
    "level_acquired": "Lv. 96",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 130.Combo Action: True Thrust or Raiden ThrustCombo Potency: 340",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/a5743cd6a29dd664a044690a6e98f3ddeb05eb5a.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Spiral Blow",
    "level_acquired": "Lv. 96",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.Combo Action: True Thrust or Raiden ThrustCombo Potency: 300Combo Bonus: Grants Power SurgePower Surge Effect: Increases damage dealt by 10%Duration: 30s",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b87f6aa2ebc0b8c4a858b76c6be82094738a6247.png",
    "armor_type": "maiming",
    "class_type": "melee"
  },
  {
    "action_name": "Starcross",
    "level_acquired": "Lv. 100",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "20y 5y",
    "effect": "Deals physical damage to target and all enemies nearby it with a potency of 1,000 for the first enemy, and 40% less for all remaining enemies.Can only be executed while under the effect of Starcross Ready.",
    "class_name": "dragoon",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/fa02faafe16ebea100212e1ae3b89298bc249a7f.png",
    "armor_type": "maiming",
    "class_type": "melee"
  }
]
