$skills = [
  {
    "action_name": "Spinning Edge",
    "level_acquired": "Lv. 1",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 300. Additional Effect: Increases Ninki Gauge by 5",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/150bf30be1a1ae0bcb2716d0ee4db448b71609c6.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Shade Shift",
    "level_acquired": "Lv. 2",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Create shadows that nullify damage up to 20% of maximum HP. Duration: 20 s",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/cad6fe9181335338ed411e0d9a2357a6e8496efc.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Gust Slash",
    "level_acquired": "Lv. 4",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 240. Combo Action: Spinning Edge Combo Potency: 400 Combo Bonus: Increases Ninki Gauge by 5",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7891f6fad42ffdcf2a4f2b1fa37570c9a1f3a1a9.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Hide",
    "level_acquired": "Lv. 10",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "20s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Blend in with your surroundings, making it impossible for most enemies to detect you, but reducing movement speed by 50%. Has no effect on enemies 10 levels higher than your own, or certain enemies with special sight. Additional Effect: Restores 2 charges to all mudra The effect of Doton ends upon execution of Hide. Cannot be executed while in combat. Effect ends upon use of any action other than Sprint, or upon reuse of Hide.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5b5c3b6be21935b60b3e60b8b2b473fd3c0a7530.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Throwing Dagger",
    "level_acquired": "Lv. 15",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Delivers a ranged attack with a potency of 200. Additional Effect: Increases Ninki Gauge by 5",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e3d6094d93d1e6f8cb9034229a9f4bed0571471b.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Mug",
    "level_acquired": "Lv. 15",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 150. Additional Effect: Increases target's damage taken by 5% Duration: 20 s Additional Effect: Increases the chance of additional items being dropped by target if Mug is dealt before, or as, the finishing blow",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b36d71590151a6f7f3d5fd616933f452bc9eeb68.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Trick Attack",
    "level_acquired": "Lv. 18",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 300. 400 when executed from a target's rear. Additional Effect: Increases damage you deal target by 10% Duration: 15 s Can only be executed while under the effect of Hidden.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/820c1eb36bd9488505973d7141d73e7fa1c3d1db.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Aeolian Edge",
    "level_acquired": "Lv. 26",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 220. 280 when executed from a target's rear. Combo Action: Gust Slash Combo Potency: 400 Rear Combo Potency: 460 Potencies are increased by 100 while under the effect of Kazematoi. Combo Bonus: Increases Ninki Gauge by 15",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c2741e8be4448134b1497cf59fa8a32d096cb91e.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Ten",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "20s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Make the ritual mudra hand gesture for \"heaven.\"Duration: 6 s Maximum Charges: 2 Triggers the cooldown of weaponskills, mudra, and Ninjutsu upon execution. Conversely, execution of weaponskills triggers the cooldown of this action.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/55c66e798d7404567ec69a023335542cef7cd916.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Ninjutsu",
    "level_acquired": "Lv. 30",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1.5s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Executes a specific ninjutsu action coinciding with the combination of mudra made immediately beforehand. If any other action is used before the mudra are combined and the ninjutsu executed, Ninjutsu will fail. Triggers the cooldown of weaponskills, mudra, and Ninjutsu upon execution. Conversely, execution of weaponskills triggers the cooldown of this action. Restores 2 charges to all mudra when Hide is executed while outside of combat.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b1362c998dbfc19dfd13223d2ae275be7f4db7cc.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Chi",
    "level_acquired": "Lv. 35",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "20s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Make the ritual mudra hand gesture for \"earth.\"Duration: 6 s Maximum Charges: 2 Triggers the cooldown of weaponskills, mudra, and Ninjutsu upon execution. Conversely, execution of weaponskills triggers the cooldown of this action.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1836df5cdf1d1f78ae7b2f65462661f2fa6a79d8.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Death Blossom",
    "level_acquired": "Lv. 38",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 100 to all nearby enemies. Additional Effect: Increases Ninki Gauge by 5",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/08a91ba599c83a9fdbe791137d57f411f130bcc3.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Assassinate",
    "level_acquired": "Lv. 40",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 200.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c8f030128bce9d193521eb5cfcd9ff4636bbea61.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Shukuchi",
    "level_acquired": "Lv. 40",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Move quickly to the specified location. Maximum Charges: 2 Cannot be executed while bound.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/ea2717bad5b805b35bb32731d78113692104a30d.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Jin",
    "level_acquired": "Lv. 45",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "20s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Make the ritual mudra hand gesture for \"man.\"Duration: 6 s Maximum Charges: 2 Triggers the cooldown of weaponskills, mudra, and Ninjutsu upon execution. Conversely, execution of weaponskills triggers the cooldown of this action.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/2183f2672edde169e6276764503ec11ae06b4c1e.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Kassatsu",
    "level_acquired": "Lv. 50",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Allows the execution of a single ninjutsu without consumption of mudra charges. Additional Effect: Increases damage for the next ninjutsu action by 30% Duration: 15 s Recast timer of mudra is not affected by the execution of this action.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/a12553440d7385aaafc940cac8f14682e3012392.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Hakke Mujinsatsu",
    "level_acquired": "Lv. 52",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 100 to all nearby enemies. Combo Action: Death Blossom Combo Potency: 120 Combo Bonus: Increases Ninki Gauge by 5",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/86e59c1bd3dedee2a6b68d3321da04c68a3acb52.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Armor Crush",
    "level_acquired": "Lv. 54",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 240. 300 when executed from a target's flank. Combo Action: Gust Slash Combo Potency: 440 Flank Combo Potency: 500 Combo Bonus: Grants 2 stacks of Kazematoi Kazematoi Effect: Increases potency of Aeolian Edge by 100 Maximum Stacks: 5 Combo Bonus: Increases Ninki Gauge by 15",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/f8e49f627d8f6e16b91b2192b322812f09c40475.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Dream Within a Dream",
    "level_acquired": "Lv. 56",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers a threefold attack, each hit with a potency of 180.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/f2e750bda00af60c3a06480f512753c8b6d5951b.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Hellfrog Medium",
    "level_acquired": "Lv. 62",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "25y 6y",
    "effect": "Deals fire damage with a potency of 250 to target and all enemies nearby it. Ninki Gauge Cost: 50 Shares a recast timer with Bhavacakra.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c802df3d7abd5e50889d1cc5e97cf64eb1610afa.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Dokumori",
    "level_acquired": "Lv. 66",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "8y 8y",
    "effect": "Delivers an attack to all enemies in a cone before you with a potency of 400. Additional Effect: Increases target's damage taken by 5% Duration: 20 s Additional Effect: Increases the chance of additional items being dropped by target if Dokumori is dealt before, or as, the finishing blow Additional Effect: Increases Ninki Gauge by 40 Additional Effect: Grants Higi Duration: 30 s",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/751e11fc60c05f5ac427b522211ae510ef845f6c.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Bhavacakra",
    "level_acquired": "Lv. 68",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Deals unaspected damage with a potency of 400. Meisui Bonus: Potency is increased to 550 when under the effect of Meisui Ninki Gauge Cost: 50 Shares a recast timer with Hellfrog Medium.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7fa8283b30b9ac35aada60984cbfaf01d3268c95.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Ten Chi Jin",
    "level_acquired": "Lv. 70",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Temporarily converts each of the three mudra into a ninjutsu action. Executing one of these actions will convert the remaining mudra into different ninjutsu actions until all three have been executed or the Ten Chi Jin effect expires. Duration: 6 s Additional Effect: Grants Tenri Jindo Ready Duration: 30 s Only ninjutsu available while active. The same ninjutsu cannot be executed twice. Cannot be executed while under the effect of Kassatsu.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/9c0c72efe9ba9c13d3765b1b7dd863c68eeaf4ba.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Meisui",
    "level_acquired": "Lv. 72",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Dispels Shadow Walker, increasing the Ninki Gauge by 50. Additional Effect: Grants Meisui Duration: 30 s Meisui Effect: Increases the potency of Zesho Meppo to 850 and Bhavacakra to 550 Can only be executed while in combat and under the effect of Shadow Walker.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/9c7d1c58eb10c5d105f1ee98a21f84a031d26518.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Bunshin",
    "level_acquired": "Lv. 80",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "90s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Grants 5 stacks of Bunshin, each stack allowing your shadow to attack enemies each time you execute a weaponskill. Shadow attack potency varies based on the attack executed, but is not affected by combo bonuses. Melee Attack Potency: 160 Ranged Attack Potency: 160 Area Attack Potency: 80 Ninki Gauge increases by 5 each time your shadow lands an attack. Duration: 30 s Additional Effect: Grants Phantom Kamaitachi Ready Duration: 45 s Ninki Gauge Cost: 50",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/d74531599ce1fc1886de7c5302265b73dd45accb.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Phantom Kamaitachi",
    "level_acquired": "Lv. 82",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Your shadow deals wind damage to target and all enemies within 5 yalms with a potency of 700. Additional Effect: Increases Ninki Gauge by 10 Can only be executed while under the effect of Phantom Kamaitachi Ready.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/384071d47821ff848b0433515b14bce679ca72ae.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Hollow Nozuchi",
    "level_acquired": "Lv. 86",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "0",
    "mp_cost": "0",
    "radius": "100y 5y",
    "effect": "All enemies standing in the corrupted earth of Doton take additional earth damage with a potency of 70. Requires Hakke Mujinsatsu to be executed as a combo action or upon executing Katon, Goka Mekkyaku, or Phantom Kamaitachi. Effect can only be triggered while Doton is active.※This action cannot be assigned to a hotbar.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/2be5fb388f3fa8857567e83e22b8b97ad17aeb0d.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Forked Raiju",
    "level_acquired": "Lv. 90",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Rushes target and delivers a lightning attack with a potency of 700. Additional Effect: Increases Ninki Gauge by 5 Can only be executed while under the effect of Raiju Ready. Cannot be executed while bound.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5eb233e8637d859bc6c0803ffef792f272692176.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Fleeting Raiju",
    "level_acquired": "Lv. 90",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.12s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Deals lightning damage with a potency of 700. Additional Effect: Increases Ninki Gauge by 5 Can only be executed while under the effect of Raiju Ready.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5b620ecc1931b456fea19bbc787a7848a9ce77a6.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Kunai's Bane",
    "level_acquired": "Lv. 92",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "3y 5y",
    "effect": "Deals damage to target and all enemies nearby it with a potency of 700. Additional Effect: Afflicts target with Kunai's Bane Kunai's Bane Effect: Increases damage you deal target by 10% Duration: 15 s Can only be executed while Hidden.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/70139d7c1c6e323518d56f1bd503a9e8bc94d21b.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Deathfrog Medium",
    "level_acquired": "Lv. 96",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "25y 6y",
    "effect": "Deals fire damage with a potency of 400 to target and all enemies nearby it. Ninki Gauge Cost: 50 Can only be executed while under the effect of Higi. Shares a recast timer with Bhavacakra.※This action cannot be assigned to a hotbar.※Hellfrog Medium changes to Deathfrog Medium when requirements for execution are met.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/cb1fc6f802ae442daa8ead243f4f9f49bf9525f4.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Zesho Meppo",
    "level_acquired": "Lv. 96",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Deals unaspected damage with a potency of 700. Meisui Bonus: Potency is increased to 850 Ninki Gauge Cost: 50 Can only be executed while under the effect of Higi. Shares a recast timer with Hellfrog Medium.※This action cannot be assigned to a hotbar.※Bhavacakra changes to Zesho Meppo when requirements for execution are met.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/55604bbe9cf720982be6e0ef74e9bf002d939935.png",
    "armor_type": "scouting",
    "class_type": "melee"
  },
  {
    "action_name": "Tenri Jindo",
    "level_acquired": "Lv. 100",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "20y 5y",
    "effect": "Deals unaspected damage to target and all enemies nearby it with a potency of 1,100. Can only be executed while under the effect of Tenri Jindo Ready.※This action cannot be assigned to a hotbar.※Ten Chi Jin changes to Tenri Jindo when requirements for execution are met.",
    "class_name": "ninja",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/7604dd447d3b450e4816e62d5bf4e2f83fafabc4.png",
    "armor_type": "scouting",
    "class_type": "melee"
  }
]
