$skills = [
  {
    "action_name": "Hakaze",
    "level_acquired": "Lv. 1",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 200.Additional Effect: Increases Kenki Gauge by 5",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/55c0a798d2db426ad407ab0d506fae3afe14cd1d.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Jinpu",
    "level_acquired": "Lv. 4",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.Combo Action: GyofuCombo Potency: 300Combo Bonus: Grants FugetsuFugetsu Effect: Increases damage dealt by 13%Duration: 40sCombo Bonus: Increases Kenki Gauge by 5",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/2cdd1c3fa2b166f8da269d9e3241399d3a37f959.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Third Eye",
    "level_acquired": "Lv. 6",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "15s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Reduces the amount of damage taken by the next attack by 10%.Duration: 4sAdditional Effect: Increases Kenki Gauge by 10 when hit",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/3c97e963e92ae242000e51159d9eb749897d8a68.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Enpi",
    "level_acquired": "Lv. 15",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Delivers a ranged attack with a potency of 100.Enhanced Enpi Potency: 270Additional Effect: Increases Kenki Gauge by 10",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b2b75c383779cbd254a8bca3dbd30f2490c1d270.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Shifu",
    "level_acquired": "Lv. 18",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 140.Combo Action: GyofuCombo Potency: 300Combo Bonus: Grants FukaFuka Effect: Reduces weaponskill cast time and recast time, spell cast time and recast time, and auto-attack delay by 13%Duration: 40sCombo Bonus: Increases Kenki Gauge by 5",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/64dcd53611773e2f2c981bc01877937b5331df8c.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Fuga",
    "level_acquired": "Lv. 26",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "8y 8y",
    "effect": "Delivers an attack with a potency of 90 to all enemies in a cone before you.Additional Effect: Increases Kenki Gauge by 5",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/5f181040a9d1ef66c6310a307036639fd78ef6c8.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Gekko",
    "level_acquired": "Lv. 30",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 160.210 when executed from a target's rear.Combo Action: JinpuCombo Potency: 370Rear Combo Potency: 420Combo Bonus: Increases Kenki Gauge by 10Combo Bonus: Grants Getsu",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/69a82466c03f3531657ce703afb8a399fdd89812.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Iaijutsu",
    "level_acquired": "Lv. 30",
    "type_of_action": "Weaponskill",
    "cast": "1.3s",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Executes a weaponskill depending on current number of Sen stored in Sen Gauge.1 Sen: Higanbana2 Sen: Tenka Goken3 Sen: Midare SetsugekkaWhile under the effect of Tendo, Tenka Goken changes to Tendo Goken, and Midare Setsugekka changes to Tendo Setsugekka.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/64757011257ac3561af53f09ffb47bd76744803d.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Mangetsu",
    "level_acquired": "Lv. 35",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 100 to all nearby enemies.Combo Action: FukoCombo Potency: 120Combo Bonus: Grants FugetsuFugetsu Effect: Increases damage dealt by 13%Duration: 40sCombo Bonus: Increases Kenki Gauge by 10Combo Bonus: Grants Getsu",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/81e6e44a8a26f2355226894a36dea570ce1d6962.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Kasha",
    "level_acquired": "Lv. 40",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 160.210 when executed from a target's flank.Combo Action: ShifuCombo Potency: 370Flank Combo Potency: 420Combo Bonus: Increases Kenki Gauge by 10Combo Bonus: Grants Ka",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/8330058e7e147dc2093e838239c2865aea6d6166.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Oka",
    "level_acquired": "Lv. 45",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 100 to all nearby enemies.Combo Action: FukoCombo Potency: 120Combo Bonus: Grants FukaFuka Effect: Reduces weaponskill cast time and recast time, spell cast time and recast time, and auto-attack delay by 13%Duration: 40sCombo Bonus: Increases Kenki Gauge by 10Combo Bonus: Grants Ka",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/83caa2b18aa8a589ccdd81b8367452ef73d1e2b2.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Yukikaze",
    "level_acquired": "Lv. 50",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 160.Combo Action: GyofuCombo Potency: 340Combo Bonus: Increases Kenki Gauge by 15Combo Bonus: Grants Setsu",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/353a35cad8a1e089d162451dbe5de1fb78f4b0a9.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Meikyo Shisui",
    "level_acquired": "Lv. 50",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "55s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Execute up to 3 weaponskill combos without meeting combo prerequisites. Does not affect Iaijutsu or Ogi Namikiri.Duration: 20sAdditional Effect: Successfully landing Gekko grants Fugetsu, and successfully landing Kasha grants FukaAdditional Effect: Grants TendoDuration: 30sMaximum Charges: 2",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/13e7fc6c10bb476259ec8d29d086bef49bea509c.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hissatsu: Shinten",
    "level_acquired": "Lv. 52",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 250.Kenki Gauge Cost: 25",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/c57812e667388d676fd1267d87583aa29c2da2ef.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hissatsu: Gyoten",
    "level_acquired": "Lv. 54",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "5s",
    "mp_cost": "0",
    "radius": "20y 0y",
    "effect": "Rushes target and delivers an attack with a potency of 100.Kenki Gauge Cost: 10Cannot be executed while bound.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/98f63e44032f5b66bbe9f77ad2882e38b42854b3.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hissatsu: Yaten",
    "level_acquired": "Lv. 56",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "10s",
    "mp_cost": "0",
    "radius": "5y 0y",
    "effect": "Delivers an attack with a potency of 100.Additional Effect: 10-yalm backstepAdditional Effect: Grants Enhanced EnpiDuration: 15sKenki Gauge Cost: 10Cannot be executed while bound.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/f939f0b2b36012cbc5096f6b64a787a8d5f5ed6a.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Meditate",
    "level_acquired": "Lv. 60",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Gradually increases your Kenki Gauge.Duration: 15sAdditional Effect: Grants stacks of Meditation when used in combat, up to a maximum of 3Kenki Gauge not affected when used outside battle.Effect ends upon using another action or moving (including facing a different direction).Cancels auto-attack upon execution.Triggers the cooldown of weaponskills upon execution. Cannot be executed during the cooldown of weaponskills.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4b642f7d616d6ca25a2ac0dfb230cb5f953eebd1.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hissatsu: Kyuten",
    "level_acquired": "Lv. 62",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 100 to all nearby enemies.Kenki Gauge Cost: 25",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/b0d5ff90bd65e254949741965c77d50b100b8241.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hagakure",
    "level_acquired": "Lv. 68",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "5s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Converts Setsu, Getsu, and Ka into Kenki. Each Sen converted increases your Kenki Gauge by 10. Can only be executed if under the effect of at least one of the three statuses.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/afaf9f6273e5d6a275a84ad286c390d7337cd11d.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Ikishoten",
    "level_acquired": "Lv. 68",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "120s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Increases Kenki Gauge by 50.Additional Effect: Grants Ogi Namikiri ReadyDuration: 30sAdditional Effect: Grants Zanshin ReadyDuration: 30sCan only be executed while in combat.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/9165fbf83411057b22d8d9c2a5e29dd6fd6fce5c.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hissatsu: Guren",
    "level_acquired": "Lv. 70",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Delivers an attack to all enemies in a straight line before you with a potency of 400.Kenki Gauge Cost: 25Shares a recast timer with Hissatsu: Senei.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/a6e4fbc47fbb90b64d6a58495cf991f9aad2548b.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Hissatsu: Senei",
    "level_acquired": "Lv. 72",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "60s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 800.Kenki Gauge Cost: 25Shares a recast timer with Hissatsu: Guren.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1812ee8f2135ed92057b767eacbf2469ef0b25ee.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Tsubame-gaeshi",
    "level_acquired": "Lv. 74",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Repeats the previously executed iaijutsu.Cannot be used to repeat Higanbana.Can only be executed while under the effect of Tsubame-gaeshi Ready.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/2aeabf974ab57ac123bc19cacfcd94c3ad86373a.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Shoha",
    "level_acquired": "Lv. 80",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "15s",
    "mp_cost": "0",
    "radius": "10y 10y",
    "effect": "Delivers an attack to all enemies in a straight line before you with a potency of 640 for the first enemy, and 40% less for all remaining enemies.Can only be executed after accumulating three stacks of Meditation by executing Iaijutsu, Meditate, or Ogi Namikiri while in combat.Consumes all stacks of Meditation upon execution.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/1f8f320806d886a35983a5c411ba95ede40072ce.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Tengentsu",
    "level_acquired": "Lv. 82",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "15s",
    "mp_cost": "0",
    "radius": "0y 0y",
    "effect": "Reduces the amount of damage taken by the next attack by 10%.Duration: 4sAdditional Effect: Grants Tengentsu's Foresight and increases Kenki Gauge by 10 when hitTengentsu's Foresight Effect: Gradually restores your HP and reduces damage taken by 10%Duration: 9sCure Potency: 200",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/e19cabdcde1b0f098413243188fac82350642f89.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Fuko",
    "level_acquired": "Lv. 86",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "0y 5y",
    "effect": "Delivers an attack with a potency of 100 to all nearby enemies.Additional Effect: Increases Kenki Gauge by 10",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/db60b934788a92fdfd9bf4b749c5c7ab80a56d03.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Ogi Namikiri",
    "level_acquired": "Lv. 90",
    "type_of_action": "Weaponskill",
    "cast": "1.3s",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "8y 8y",
    "effect": "Delivers a critical hit to all enemies in a cone before you with a potency of 1,000 for the first enemy, and 40% less for all remaining enemies.Damage dealt is increased when under an effect that raises critical hit rate.Grants a stack of Meditation, up to a maximum of 3.Can only be executed while under the effect of Ogi Namikiri Ready.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/08d676ac5d79d9f433c8ebc11ff39fa40246ae2b.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Kaeshi: Namikiri",
    "level_acquired": "Lv. 90",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "8y 8y",
    "effect": "Delivers a critical hit to all enemies in a cone before you with a potency of 1,000 for the first enemy, and 40% less for all remaining enemies.Damage dealt is increased when under an effect that raises critical hit rate.※This action cannot be assigned to a hotbar.※Ogi Namikiri changes to Kaeshi: Namikiri when requirements for execution are met.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/63536deb9e8a888c17e4b367bff095cc0f3c2740.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Gyofu",
    "level_acquired": "Lv. 92",
    "type_of_action": "Weaponskill",
    "cast": "Instant",
    "recast": "2.5s",
    "mp_cost": "0",
    "radius": "3y 0y",
    "effect": "Delivers an attack with a potency of 240.Additional Effect: Increases Kenki Gauge by 5",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/ddb014de5732830d67f200a551b9e53a5537c3b7.png",
    "armor_type": "striking",
    "class_type": "melee"
  },
  {
    "action_name": "Zanshin",
    "level_acquired": "Lv. 96",
    "type_of_action": "Ability",
    "cast": "Instant",
    "recast": "1s",
    "mp_cost": "0",
    "radius": "8y 8y",
    "effect": "Delivers an attack to all enemies in a cone before you with a potency of 940 for the first enemy, and 40% less for all remaining enemies.Kenki Gauge Cost: 50Can only be executed while under the effect of Zanshin Ready.",
    "class_name": "samurai",
    "image_url": "https://lds-img.finalfantasyxiv.com/d/4f7a3ffda80a03425ae8a4001c4f4c2412012047.png",
    "armor_type": "striking",
    "class_type": "melee"
  }
]
